name: 🚀 Innerpece(Laravel) Deploy to Hostinger via SFTP

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🗂️ Upload Innerpece Files via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 65002
          source: "./"
          target: "/var/www/backoffice-innerpece/"  # Adjust if your root folder is different
          rm: false
          strip_components: 0
          overwrite: true
          exclude: |
            vendor
            node_modules
