name: 🚀 Innerpece(Laravel) Deploy to Hostinger via SFTP

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🗂️ Upload Innerpece Files via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: sftp
          port: 22
          server-dir: ${{ secrets.FTP_REMOTE_DIR }}
          active: false
          dangerous-clean-slate: false
          local-dir: ./
          exclude: |
            **/vendor/**
            **/vendor*/**
