name: 🚀 Innerpece(Laavel) Deploy to Hostinger via FTP

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3

      - name: 🗂️ Upload Laravel Files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          server-dir: ${{ secrets.FTP_REMOTE_DIR }}
          local-dir: ./
          exclude: |
            **/.git*
            **/.github*
            **/ node_modules/*
             **/tests/*
           **/  storage/logs/*
            **/ storage/framework/*
            **/ vendor/*
